---
app:
  name: library
  version: 1.0.0

quarkus:
  datasource:
    db-kind: mariadb
    username: librarian
    jdbc:
      url: jdbc:mariadb://pandora.hq.kaiserpfalz-edv.de:3306/librarian_library?useLegacyDatetimeCode=false&serverTimezone=UTC
      max-size: 16
  hibernate-orm:
    database:
      generation: validate
  liquibase:
    migrate-at-start: true
    change-log: db/changeLog.xml

"%dev": &dev
  quarkus:
    http:
      port: 8091
      test-port: 8091
      ssl-port: 8453
      test-ssl-port: 8453

    log:
      console:
        json: false

"%test": *dev